spring:
  application:
    name: weatherforecast
server:
  port: 7004
  servlet:
    context-path: /weatherforecast
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5060/eureka/eureka