spring:
  application:
    name: weatherdisaster
server:
  port: 7006
  servlet:
    context-path: /weatherdisaster
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5060/eureka/eureka