spring:
  application:
    name: actualweather
server:
  port: 7003
  servlet:
    context-path: /actualweather
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5060/eureka/eureka